### ISSUE TITLE
First reaction examples

### ISSUE THREAD

**Issue by slwu89** [adolgert/Fleck.jl#11]
If I understand correctly, the first reaction method should be good to go immediately to start implementing semi-Markov examples. We'd want a couple to show off some common cases:

1. homogeneous Markov (in the PR #10)
2. inhomogeneous Markov (e.g. SIR with $\beta$ following a sine curve for "seasonality")
3. homogeneous semi-Markov with Dirac distribution (e.g. SIR but with deterministic I to R transition)
4. inhomogeneous semi-Markov (e.g. example 2 but with some non-exponential distribution on the I to R transition)

There are more of interest, but these should be sufficient for now. Using the Dirac distribution means that we'd want to be able to support [MeasureTheory.jl](https://github.com/cscherrer/MeasureTheory.jl) which implements a Dirac "distribution". See a very silly example I made here of using Dirac distributions as the transition kernel of a Markov chain to simply count on the integers, perhaps one of the most baroque ways to count on the integers  https://gist.github.com/slwu89/a54ad60c047fad23741213ce7aa09e97

**Comment by slwu89** [comment]
Edit: we can hold off on supporting MeasureTheory for now, this is apparently in Distributions.jl (TIL) https://juliastats.org/Distributions.jl/stable/univariate/#Distributions.Dirac

MeasureTheory.jl won't actually be that useful for Fleck. At least at this stage.

**Comment by slwu89** [comment]
There is an interesting question here of how to deal with something like the I to R transition with a Dirac distribution. As soon as a new token arrives in I it will become enabled, with a new firing time at that time plus the deterministic delay. There's a few ways to handle it, including keeping a priority queue of "finishing times". Another way is to make an entirely new clock object just for that event. But whatever method should be able to handle interruptions (e.g. what if there is an I to death clock as well, with an exponential clock on it). This is worth a discussion.

**Comment by slwu89** [comment]
Putting many of these into `notes`, see branch https://github.com/adolgert/Fleck.jl/tree/docs/notes

**Comment by adolgert** [comment]
Hey, I see the notes and will read them next. Yes, the first reaction is just fine. Next reaction needs testing. I think the FirstToFire will be the fastest and also not so complicated it will be tough to test.
