### ISSUE TITLE
CI triggers

### ISSUE THREAD

**Issue by slwu89** [adolgert/Fleck.jl#13]
I suggest that we only trigger CI runs when doing something like opening a PR to `main`, I tend to commit frequently when working and I don't necessarily expect every commit will pass, and would rather only trigger CI when I'm ready to open a PR for a block of work that I think is nearing completion and has a good chance of passing.

**Comment by adolgert** [comment]
Ah, fine. That's an old habit from when the CI was an internal server, so it was basically free information. It's a good idea.
