### ISSUE TITLE
abstract type for samplers

### ISSUE THREAD

**Issue by slwu89** [adolgert/Fleck.jl#37]
This is highly related to #35; we should have an abstract sampler type. This helps users write applications using the library, for example, a user might reasonably want to do something like:

```julia
function myfunc(sampler::AbstractSampler{KeyType}) where {KeyType}
   # do something with KeyType
end
```

**Comment by slwu89** [comment]
There is already an abstract type `SSA{Key,Time]` in https://github.com/adolgert/Fleck.jl/blob/main/src/sample/sampler.jl, so we need to make the other types be subtypes of it and make sure all the generic interface elements only need a type of `<:SSA`.

**Comment by slwu89** [comment]
@adolgert as a prelude to doing #36 I want to do this one first. Is `SSA` the right abstract type that other samplers (e.g. `FirstToFire`) should be subtypes of in order to develop a generic interface?

**Comment by adolgert** [comment]
Hi Sean. Yes, SSA is the right type. I think this is a good one to do, and I'll leave 36 to you if you want. - Drew

**Comment by slwu89** [comment]
Great, I'll work on these two issues in the same PR then.
