### ISSUE TITLE
issue with make.jl

### ISSUE THREAD

**Issue by slwu89** [adolgert/Fleck.jl#54]
@adolgert when running `docs/make.jl` for some reason the distributions.md and various pngs from it are still being dumped into `docs/src/` which will mess up the deployment. Not sure why.

![image](https://github.com/adolgert/Fleck.jl/assets/10673535/af51b431-ef34-4bf0-a60b-5bee55a2c3ca)

**Comment by adolgert** [comment]
Sean, Literate considers each image a "chunk" and the only option I see is to put the chunks in the same directory as the output Markdown file. We can set the "outputdir" for both to be another directory. Does that help?

https://github.com/fredrikekre/Literate.jl/blob/ce7e21d3c2457d955324ebee3a84271c38b4117f/src/Literate.jl#L584

**Comment by slwu89** [comment]
Oh, then it's my misunderstanding. I thought that it was polluting that directory, and that it was a bug. Nevermind, closing this issue then.
